name: CI


on:
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install root dependencies
        run: npm i

      - name: Run lint and tests
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

  push_to_docker_hub:
    runs-on: ubuntu-latest

    needs: [build_test]

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: archcry/somfy-automation:latest
